[package]
name = "sgl"
version = "0.1.0"
authors = ["Ella-0 <23418164+Ella-0@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "*"
ansi_term = "*"
